site_name: Dansebox Modding API Documentation
site_url: https://antikoredev.github.io/dbdocs
repo_url: https://github.com/antikoredev/dbdocs
site_description: This is an official documentation for Dansebox's modding API created using MkDocs
site_author: Antikore
nav:
  - Home: home
theme: readthedocs